const { DataTypes } = require("sequelize");
const sequelize = require("../configs/sequelize");

const admission = sequelize.define("Admission", {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
  },
  name: {
    type: DataTypes.STRING,
  },
  photo: { type: DataTypes.STRING },
  gender: { type: DataTypes.STRING },
  bloodGroup: { type: DataTypes.STRING },
  DOB: { type: DataTypes.DATE },
  Mob1: { type: DataTypes.STRING },
  Mob2: { type: DataTypes.STRING },
  email: { type: DataTypes.STRING },
  aadhar: { type: DataTypes.STRING },
  fname: { type: DataTypes.STRING },
  focc: { type: DataTypes.STRING },
  mname: { type: DataTypes.STRING },
  mocc: { type: DataTypes.STRING },
  branch: { type: DataTypes.STRING },
  minDetail: { type: DataTypes.STRING },
  phyChall: { type: DataTypes.STRING },
  JEEAR: { type: DataTypes.INTEGER },
  JEER: { type: DataTypes.STRING },
  JEES: { type: DataTypes.INTEGER },
  AlloctCat: { type: DataTypes.STRING },
  CandCat: { type: DataTypes.STRING },
  JoDD: { type: DataTypes.STRING },
  JoDate: { type: DataTypes.DATEONLY },
  JoAmount: { type: DataTypes.FLOAT },
  InDD: { type: DataTypes.STRING },
  InDate: { type: DataTypes.DATEONLY },
  InAmount: { type: DataTypes.FLOAT },
  cAdd: { type: DataTypes.STRING },
  cCity: { type: DataTypes.STRING },
  cState: { type: DataTypes.STRING },
  cPin: { type: DataTypes.STRING },
  cMob: { type: DataTypes.STRING },
  pAdd: { type: DataTypes.STRING },
  pCity: { type: DataTypes.STRING },
  pState: { type: DataTypes.STRING },
  pPin: { type: DataTypes.STRING },
  pMob: { type: DataTypes.STRING },
  sscb: { type: DataTypes.STRING },
  sscs: { type: DataTypes.STRING },
  sscy: { type: DataTypes.INTEGER },
  sscm: { type: DataTypes.FLOAT },
  sscp: { type: DataTypes.STRING },
  hscb: { type: DataTypes.STRING },
  hscs: { type: DataTypes.STRING },
  hscy: { type: DataTypes.INTEGER },
  hscm: { type: DataTypes.FLOAT },
  hscp: { type: DataTypes.STRING },
  uploaded: { type: DataTypes.STRING },
  chronicD: { type: DataTypes.STRING },
  dec: { type: DataTypes.STRING },
  sign: { type: DataTypes.STRING },
});

module.exports = admission;
